'use client';
import {useState,useId} from 'react';
import {House,FileText,Wrench,CalendarDays,Users,ArrowLeft,ChevronRight,Plus,MessageCircle,UserRound,Search,Bell,Check,Camera,Wifi,BatteryFull,ArrowUpRight} from 'lucide-react';
import Brand from './Brand';
import {roles,type Role} from '@/lib/data';
import {Button} from './ui/button';
type Screen='home'|'house'|'repair'|'records'|'my'|'chat'|'add'|'documents'|'contacts'|'schedule'|'points'|'settings';
const titles:Record<Screen,string>={home:'홈',house:'우리집',repair:'수리관리',records:'집의 기록',my:'나의 집신',chat:'집신 톡',add:'기록 추가',documents:'계약문서',contacts:'연락처',schedule:'일정관리',points:'나의 Z',settings:'설정'};
export default function PhoneDemo({role='agent'}:{role?:Role}){const[screen,setScreen]=useState<Screen>('home');const[status,setStatus]=useState(1);const[added,setAdded]=useState(false);const[query,setQuery]=useState('');const id=useId();const r=roles[role];const recent=[...(added?['새 메모를 추가했어요']:[]),'보일러 수리 완료','욕실 사진 4장 등록','계약서 등록','수리기사 방문'];
 const go=(s:Screen)=>{setScreen(s);setQuery('')};
 return <div className="phone" aria-label={`${r.label} 집신 체험 화면`}><div className="phone-status"><span>9:41</span><span className="island"/><span><Wifi size={13}/><BatteryFull size={17}/></span></div><div className="phone-top"><Brand/><button aria-label="데모 알림 보기" onClick={()=>go('schedule')}><Bell size={19}/><i/></button></div><div className="phone-body">
 {screen==='home'?<><label className="demo-search" htmlFor={id}><Search size={15}/><input id={id} placeholder="집 · 사람 · 기사 · 기록 검색" value={query} onChange={e=>setQuery(e.target.value)}/></label>{query?<div className="search-results"><h4>검색 결과</h4>{['월계동 아파트 1203호','서울집신 공인중개사','보일러 수리 완료','욕실 사진','계약서','김집신 기사'].filter(x=>x.includes(query)).map(x=><button key={x} onClick={()=>go(x.includes('기사')?'contacts':x.includes('수리')?'repair':'house')}>{x}<ChevronRight size={16}/></button>)}{!['월계동 아파트 1203호','서울집신 공인중개사','보일러 수리 완료','욕실 사진','계약서','김집신 기사'].some(x=>x.includes(query))&&<p>일치하는 체험 자료가 없습니다.</p>}</div>:<><div className={`demo-summary ${role==='tenant'?'tenant-summary':''}`}><span className="demo-role">{r.label}</span><h3>{r.home}</h3><p>{r.badge}</p><div className="demo-stats">{r.stats.map(([label,n])=><button key={label} onClick={()=>go(label.includes('일정')||label.includes('방문')?'schedule':'repair')}><span>{label}</span><b>{n}<small>건</small></b></button>)}</div></div><button className="house-link" onClick={()=>go('house')}><House size={22}/><span><b>{role==='tenant'?'거주 중인 집 기록':'우리집 보기'}</b><small>집의 기록을 한눈에</small></span><ChevronRight size={16}/></button><h4>자주 사용하는 기능</h4><div className="quick-grid">{([{icon:FileText,label:role==='repair'?'의뢰목록':'계약문서',to:'documents'},{icon:Wrench,label:'수리관리',to:'repair'},{icon:Users,label:'연락처',to:'contacts'},{icon:CalendarDays,label:'일정관리',to:'schedule'}] as const).map(({icon:Icon,label,to})=><button key={to} onClick={()=>go(to)}><Icon/><span>{label}</span><ChevronRight size={12}/></button>)}</div><div className="recent-heading"><h4>최근 기록</h4><button onClick={()=>go('records')}>전체 보기 <ChevronRight size={12}/></button></div><button className="recent-card" onClick={()=>go('repair')}><span className="icon-tile"><Wrench size={18}/></span><span><b>보일러 수리 완료</b><small>월계동 아파트 · 오늘 10:15</small></span><span className="done-badge">완료</span></button></> }</>:<><button className="demo-back" onClick={()=>go('home')}><ArrowLeft size={17}/>{titles[screen]}</button>
 {screen==='house'&&<><div className="detail-head"><House/><span>나의 집</span><h3>월계동 아파트 1203호</h3><p>전세 · 현재 거주 중</p><strong className="dday">만기 D-187</strong></div><div className="detail-stats"><button onClick={()=>go('repair')}>수리 요청 <b>1건</b></button><button onClick={()=>go('schedule')}>예정 일정 <b>1건</b></button><button onClick={()=>go('documents')}>보증 자료 <b>3건</b></button></div><h4>최근 기록</h4>{['수도 수리 완료','욕실 사진 등록','계약서 등록'].map(t=><button className="demo-row" key={t} onClick={()=>go(t.includes('수리')?'repair':'records')}><Check size={16}/>{t}<ChevronRight size={14}/></button>)}</>}
 {screen==='repair'&&<><div className="detail-head"><span>월계동 아파트 1203호</span><h3>욕실 누수</h3><p>욕실 세면대 아래에서 물이 새요.</p></div><div className="repair-steps">{['접수','처리중','완료'].map((s,i)=><button className={status===i?'selected':''} key={s} onClick={()=>setStatus(i)}><span>{i+1}</span>{s}</button>)}</div><p className="demo-hint">단계를 눌러 처리 상태를 바꿔보세요.</p><dl className="repair-info">{[['요청일','9월 21일'],['방문 예정','9월 23일 14:00'],['처리 완료',status===2?'9월 23일':'처리 중'],['예상 비용','80,000원'],['영수증',status===2?'등록 완료':'완료 후 등록']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="photo-slots"><span><Camera/>수리 전 사진 예시</span><span><Check/>수리 후 사진 예시</span></div></>}
 {screen==='records'&&<><p className="demo-hint">집의 변화가 시간순으로 쌓입니다.</p><div className="timeline">{recent.map((t,i)=><button key={t} onClick={()=>go(t.includes('수리')?'repair':'documents')}><span>{['오늘','어제','9월 21일','9월 18일'][i]||'오늘'}</span><strong>{t}</strong><small>월계동 아파트 1203호</small></button>)}</div></>}
 {screen==='my'&&<><div className="profile"><UserRound/><h3>반가워요, 집신님</h3><span>{r.label} · 체험 계정</span></div>{([['내 정보','settings'],['내 집','house'],['연락처','contacts'],['요금제','points'],['Z','points'],['설정','settings']] as [string,Screen][]).map(([t,s])=><button className="demo-row" key={t} onClick={()=>go(s)}>{t}<ChevronRight size={16}/></button>)}</>}
 {screen==='chat'&&<><p className="demo-hint">대화 화면 예시입니다. 메시지는 전송되지 않습니다.</p><div className="chat-bubble">안녕하세요. 내일 오후 2시에 방문드리겠습니다.<small>김집신 기사 · 13:20</small></div><div className="chat-bubble own">네, 방문 전에 연락 부탁드립니다.<small>집신님 · 13:22</small></div></>}
 {screen==='add'&&<><h3>어떤 기록을 남길까요?</h3><p className="demo-hint">체험 기록은 새로고침하면 사라집니다.</p><Button className="demo-add" onClick={()=>{setAdded(true);go('records')}}><Plus/>메모 예시 추가하기</Button><button className="demo-row" onClick={()=>go('repair')}><Wrench size={18}/>수리 요청 예시 보기<ChevronRight size={16}/></button></>}
 {screen==='documents'&&<><h3>집에 연결된 문서</h3>{['전세 계약서','보증 관련 자료','수리 영수증'].map((t,i)=><div className="document-row" key={t}><FileText/><span><b>{t}</b><small>{i+1}개 문서 · 체험용 예시</small></span></div>)}<p className="demo-hint">실제 파일 열기·업로드는 정식 서비스에서 제공할 예정입니다.</p></>}
 {screen==='contacts'&&<><h3>집과 연결된 사람들</h3>{['서울집신 공인중개사','김집신 임대인','김집신 수리기사'].map(t=><div className="document-row" key={t}><UserRound/><span><b>{t}</b><small>연락처 미공개 · 체험용 예시</small></span></div>)}</>}
 {screen==='schedule'&&<><h3>오늘의 일정</h3>{[['09:30','월계동 누수 점검'],['14:00','보일러 수리 방문']].map(([time,t])=><div className="schedule-row" key={t}><strong>{time}</strong><span>{t}</span></div>)}<div className="detail-head"><CalendarDays/><h3>계약 만기 D-187</h3><p>월계동 아파트 1203호</p></div></>}
 {screen==='points'&&<><div className="detail-head"><span>현재 체험 요금제</span><h3>FREE</h3><p>거주 중인 집 1채 무료</p></div><h3>기록할수록 쌓이는 Z</h3><p className="demo-hint">가입·활동 적립과 사용 혜택은 준비 중입니다. 적립 기준은 출시 시 안내합니다.</p><a className="demo-row" href="#pricing">전체 요금제 보기<ArrowUpRight size={18}/></a></>}
 {screen==='settings'&&<><h3>체험 계정 안내</h3><p className="demo-hint">개인정보를 사용하지 않는 예시 화면입니다.</p><Button variant="outline" onClick={()=>{setAdded(false);setStatus(1);go('home')}}>체험 초기화</Button></>}
 </> }</div><nav className="phone-nav" aria-label={`${r.label} 데모 하단 메뉴`}>{([{s:'home',label:'홈',icon:House},{s:'records',label:'기록',icon:FileText},{s:'add',label:'추가',icon:Plus},{s:'chat',label:'채팅',icon:MessageCircle},{s:'my',label:'마이',icon:UserRound}] as const).map(({s,label,icon:Icon})=><button key={s} aria-label={label} aria-current={screen===s?'page':undefined} onClick={()=>go(s)} className={`${s==='add'?'add-tab':''} ${screen===s?'active':''}`}><Icon size={20}/><span>{label}</span></button>)}</nav><div className="home-indicator"/></div>
}
